### ISSUE TITLE
build for py27, py35, py36, py37

### ISSUE THREAD

**Issue by prjemian** [prjemian/pyRestTable#15]
Need to add a `conda_build_config.yaml` such as [this example](https://github.com/BCDA-APS/apstools/blob/master/conda-recipe/conda_build_config.yaml) naming all these versions.

**Comment by prjemian** [comment]
@carterbox  : Thanks for the words of encouragement!

Great.  This built as follows:

```
/home/mintadmin/Apps/anaconda/conda-bld/linux-64/pyresttable-2017.2.0-py27_0.tar.bz2
/home/mintadmin/Apps/anaconda/conda-bld/linux-64/pyresttable-2017.2.0-py37_0.tar.bz2
/home/mintadmin/Apps/anaconda/conda-bld/linux-64/pyresttable-2017.2.0-py35_0.tar.bz2
/home/mintadmin/Apps/anaconda/conda-bld/linux-64/pyresttable-2017.2.0-py36_0.tar.bz2
```

Now need to build for other OS.

**Comment by prjemian** [comment]
Consider a `noarch` build: https://www.anaconda.com/condas-new-noarch-packages/

To build a noarch Python package, specify noarch in your meta.yaml:

    build:
      noarch: python

**Comment by carterbox** [comment]
There's a more detailed description of when packages can be moved to `noarch` on the [conda-forge docs](https://conda-forge.readthedocs.io/en/latest/meta.html#building-noarch-packages).

**Comment by prjemian** [comment]
building with this command:

    conda build  conda-recipe 2>&1 | tee conda-recipe/build_log.txt

**Comment by prjemian** [comment]
uploading with this command:

    anaconda upload /home/mintadmin/Apps/anaconda/conda-bld/noarch/pyresttable-2017.2.0-py_0.tar.bz2

**Comment by prjemian** [comment]
software version built into the package is wrong, should come from git tag

removed that upload

**Comment by prjemian** [comment]
uploading with this command:

    anaconda upload /home/mintadmin/Apps/anaconda/conda-bld/noarch/pyresttable-2019.0321.0.rc2-py_0.tar.bz2

**Comment by prjemian** [comment]
@carterbox Thanks for the link.  Much better than this [bolloxed](https://www.anaconda.com/condas-new-noarch-packages/) report.  This is my final [`meta.yaml`](https://github.com/prjemian/pyRestTable/blob/master/conda-recipe/meta.yaml).

**Comment by carterbox** [comment]
Nice! It's very concise. Also, you probably don't need `bld.bat` and `build.sh`. Because those two scripts are the same, you can replace them with a single build line inside `meta.yaml`

**Comment by prjemian** [comment]
What would that line look like?  I tried removing the .sh file and the build failed very early.

Perhaps:

    build:
        script: python setup.py install

**Comment by prjemian** [comment]
Yup
